# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

# シェルのプロンプトの間に空行を挿入する
add_newline = true

format = """
[╭{ $username$hostname}](bold green) $directory$git_branch$git_status$battery$time$line_break$character"""

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold green'
style_root = 'bold red'

[hostname]
ssh_only = false
format = '[@$hostname]($style) '
style = 'bold green'

[character]
success_symbol = '[╰─>](bold green)'
error_symbol = '[╰─>](bold red)'

[status]
disabled = false
style = "red"
symbol = " ><"
format = "\b[$symbol$status](fg:$style)"

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'

# ref https://github.com/starship/starship/discussions/1107#discussioncomment-345147
[git_status]
style = "#f05133"
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
conflicted = "[=](fg:red)"
staged = "[+$count](fg:green)"
modified = "[!$count](fg:yellow)"
renamed = "[»$count](fg:blue)"
deleted = "[x$count](fg:red)"
untracked = "[?$count](fg:cyan)"
up_to_date = '[✓](bold green)'
stashed = "[*$count](fg:purple)"
ahead = "[⇡$count](fg:green)"
behind = "[⇣$count](fg:red)"
diverged = "[⇕$ahead_count⇣$behind_count](fg:yellow)"

[time]
disabled = false
format = '🕙 [$time]($style) '
time_format = '%m/%d %R'

[aws]
disabled = true

[gcloud]
disabled = true
